version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./logs/frontend:/app/logs  # Mapeamento do diret贸rio de logs do frontend
      - ./frontend/src:/app/src

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./logs/backend:/app/logs  # Mapeamento do diret贸rio de logs do backend
      - ./backend:/app  # Mapeamento do diret贸rio do c贸digo fonte do backend

  mailserver:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
